name: Docker-Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_SAMUEL_USERNAME }}
          password: ${{ secrets.DOCKER_SAMUEL_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t testing .

      # Step 4: Tag the Docker image
      - name: Tag Docker image
        run: docker tag testing ${{ secrets.DOCKER_SAMUEL_USERNAME }}/testing:latest

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_SAMUEL_USERNAME }}/testing:latest
