# This is a basic workflow to help you get started with Actions

name: EnvTest

on:
  workflow_dispatch:
  

env:  
  GREETING: "Hello"
  STORY: "This is a story about how my life got turned upside down"
  ENDING: "But it wasn't in West Philadelphia"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo $GREETING, $STORY
          echo $ENDING
