name: MultipleJobs
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  step1:
    env: 
      TESTING: "This exist for testing purposes"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  step2:
    env:
      STEP2TESTING: "Strictly for trying if this works"
      SECRET_SECRETS: ${{ secrets.SECRET_SECRETS }}
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print the secret key with other information
        run: |
          echo "$SECRET_SECRETS, $STEP2TESTING This runs successfully if 'This exist' is printed."
